/*
Created by	: Yana
Time		: 15 Mei 2018 21.14
*/

import java.util.Scanner;

public class KhairilIf2{
	public static void main(String[] args) {

		Scanner keyboard = new Scanner(System.in);

		int inputan, nilai1 = 1, nilai2 = 2, nilai3 = 3, nilai4 = 4, nilai5 = 5, nilai6 = 6, nilai7 = 7, nilai8 = 8, nilai9 = 9, nilai10 = 10,
			nilai11 = 11, nilai12 = 12, nilai13 = 13, nilai14 = 14, nilai15 = 15, nilai16 = 16, nilai17 = 17, nilai18 = 18, nilai19 = 19, nilai20 = 20,
			nilai21 = 21, nilai22 = 22, nilai23 = 23, nilai24 = 24, nilai25 = 25, nilai26 = 26, nilai27 = 27, nilai28 = 28, nilai29 = 29, nilai30 = 30,
			nilai31 = 31, nilai32 = 32, nilai33 = 33, nilai34 = 34, nilai35 = 35, nilai36 = 36, nilai37 = 37, nilai38 = 38, nilai39 = 39, nilai40 = 40,
			nilai41 = 41, nilai42 = 42, nilai43 = 43, nilai44 = 44, nilai45 = 45, nilai46 = 46, nilai47 = 47, nilai48 = 48, nilai49 = 49, nilai50 = 50,
			nilai51 = 51, nilai52 = 52, nilai53 = 53, nilai54 = 54, nilai55 = 55, nilai56 = 56, nilai57 = 57, nilai58 = 58, nilai59 = 59, nilai60 = 60,
			nilai61 = 61, nilai62 = 62, nilai63 = 63, nilai64 = 64, nilai65 = 65, nilai66 = 66, nilai67 = 67, nilai68 = 68, nilai69 = 69, nilai70 = 70,
			nilai71 = 71, nilai72 = 72, nilai73 = 73, nilai74 = 74, nilai75 = 75, nilai76 = 76, nilai77 = 77, nilai78 = 78, nilai79 = 79, nilai80 = 80,
			nilai81 = 81, nilai82 = 82, nilai83 = 83, nilai84 = 84, nilai85 = 85, nilai86 = 86, nilai87 = 87, nilai88 = 88, nilai89 = 89, nilai90 = 90,
			nilai91 = 91, nilai92 = 92, nilai93 = 93, nilai94 = 94, nilai95 = 95, nilai96 = 96, nilai97 = 97, nilai98 = 98, nilai99 = 99, nilai100 = 100;

		System.out.print("Masukkan nilai angka (1-100): ");
		inputan = keyboard.nextInt();
		System.out.println();

		if (inputan == nilai4) {
			
		}

		if ( inputan < nilai1 || inputan > nilai100) {
			System.out.println("Nilai diluar range");
		}
		else{
			if ( inputan == nilai1 ) {
				System.out.println(nilai1);
			}
			else if ( inputan == nilai2 ) {
				System.out.println(nilai1+ ", "+nilai2);				
			}
			else if ( inputan == nilai3 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3);				
			}
			else if ( inputan == nilai4 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ ");				
			}
			else if ( inputan == nilai5 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5);				
			}
			else if ( inputan == nilai6 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6);				
			}
			else if ( inputan == nilai7 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7);				
			}
			else if ( inputan == nilai8 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, ");				
			}
			else if ( inputan == nilai9 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9);				
			}
			else if ( inputan == nilai10 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10);				
			}
			else if ( inputan == nilai11 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11);				
			}
			else if ( inputan == nilai12 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, ");				
			}
			else if ( inputan == nilai13 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, ");				
			}
			else if ( inputan == nilai14 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14);				
			}
			else if ( inputan == nilai15 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15);				
			}
			else if ( inputan == nilai16 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, ");				
			}
			else if ( inputan == nilai17 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17);				
			}
			else if ( inputan == nilai18 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18);				
			}
			else if ( inputan == nilai19 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19);				
			}
			else if ( inputan == nilai20 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, ");				
			}
			else if ( inputan == nilai21 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21);				
			}
			else if ( inputan == nilai22 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22);				
			}
			else if ( inputan == nilai23 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23);				
			}
			else if ( inputan == nilai24 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, ");				
			}
			else if ( inputan == nilai25 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25);				
			}
			else if ( inputan == nilai26 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, ");				
			}
			else if ( inputan == nilai27 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27);				
			}
			else if ( inputan == nilai28 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, ");				
			}
			else if ( inputan == nilai29 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29);				
			}
			else if ( inputan == nilai30 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30);				
			}
			else if ( inputan == nilai31 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31);				
			}
			else if ( inputan == nilai32 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, ");				
			}
			else if ( inputan == nilai33 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33);				
			}
			else if ( inputan == nilai34 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34);				
			}
			else if ( inputan == nilai35 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35);				
			}
			else if ( inputan == nilai36 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, ");				
			}
			else if ( inputan == nilai37 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37);				
			}
			else if ( inputan == nilai38 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38);				
			}
			else if ( inputan == nilai39 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, ");				
			}
			else if ( inputan == nilai40 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, ");				
			}
			else if ( inputan == nilai41 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41);				
			}
			else if ( inputan == nilai42 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42);				
			}
			else if ( inputan == nilai43 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43);				
			}
			else if ( inputan == nilai44 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, ");				
			}
			else if ( inputan == nilai45 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45);				
			}
			else if ( inputan == nilai46 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46);				
			}
			else if ( inputan == nilai47 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47);				
			}
			else if ( inputan == nilai48 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, ");				
			}
			else if ( inputan == nilai49 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49);				
			}
			else if ( inputan == nilai50 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50);				
			}
			else if ( inputan == nilai51 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51);				
			}
			else if ( inputan == nilai52 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, ");				
			}
			else if ( inputan == nilai53 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53);				
			}
			else if ( inputan == nilai54 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54);				
			}
			else if ( inputan == nilai55 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55);				
			}
			else if ( inputan == nilai56 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56);				
			}
			else if ( inputan == nilai57 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57);				
			}
			else if ( inputan == nilai58 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58);				
			}
			else if ( inputan == nilai59 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59);				
			}
			else if ( inputan == nilai60 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, ");				
			}
			else if ( inputan == nilai61 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61);				
			}
			else if ( inputan == nilai62 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62);				
			}
			else if ( inputan == nilai63 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63);				
			}
			else if ( inputan == nilai64 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, ");				
			}
			else if ( inputan == nilai65 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, ");				
			}
			else if ( inputan == nilai66 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66);				
			}
			else if ( inputan == nilai67 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67);				
			}
			else if ( inputan == nilai68 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, ");				
			}
			else if ( inputan == nilai69 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69);				
			}
			else if ( inputan == nilai70 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70);				
			}
			else if ( inputan == nilai71 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71);				
			}
			else if ( inputan == nilai72 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, ");				
			}
			else if ( inputan == nilai73 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73);				
			}
			else if ( inputan == nilai74 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74);				
			}
			else if ( inputan == nilai75 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75);				
			}
			else if ( inputan == nilai76 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76);				
			}
			else if ( inputan == nilai77 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77);				
			}
			else if ( inputan == nilai78 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, ");				
			}
			else if ( inputan == nilai79 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79);				
			}
			else if ( inputan == nilai80 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, ");				
			}
			else if ( inputan == nilai81 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81);				
			}
			else if ( inputan == nilai82 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82);				
			}
			else if ( inputan == nilai83 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83);				
			}
			else if ( inputan == nilai84 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, ");				
			}
			else if ( inputan == nilai85 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85);				
			}
			else if ( inputan == nilai86 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86);				
			}
			else if ( inputan == nilai87 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87);				
			}
			else if ( inputan == nilai88 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, ");				
			}
			else if ( inputan == nilai89 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89);				
			}
			else if ( inputan == nilai90 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90);				
			}
			else if ( inputan == nilai91 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, ");				
			}
			else if ( inputan == nilai92 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, ");				
			}
			else if ( inputan == nilai93 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, " +nilai93);				
			}
			else if ( inputan == nilai94 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, " +nilai93+ ", " +nilai94);				
			}
			else if ( inputan == nilai95 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, " +nilai93+ ", " +nilai94+ ", " +nilai95);				
			}
			else if ( inputan == nilai96 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, " +nilai93+ ", " +nilai94+ ", " +nilai95+ ", BIZZ, ");				
			}
			else if ( inputan == nilai97 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, " +nilai93+ ", " +nilai94+ ", " +nilai95+ ", BIZZ, " +nilai97);				
			}
			else if ( inputan == nilai98 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, " +nilai93+ ", " +nilai94+ ", " +nilai95+ ", BIZZ, " +nilai97+ ", " +nilai98);				
			}
			else if ( inputan == nilai99 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, " +nilai93+ ", " +nilai94+ ", " +nilai95+ ", BIZZ, " +nilai97+ ", " +nilai98+ ", " +nilai99);				
			}
			else if ( inputan == nilai100 ) {
				System.out.println(nilai1+ ", "+nilai2+ ", " +nilai3+ ", FIZZ, " +nilai5+ ", " +nilai6+ ", " +nilai7+ ", BIZZ, " +nilai9+ ", " +nilai10+ ", " +nilai11+ ", FIZZ, FIZZBIZZ, " +nilai14+ ", " +nilai15+ ", BIZZ, " +nilai17+ ", " +nilai18+ ", " +nilai19+ ", FIZZ, " +nilai21+ ", " +nilai22+ ", " +nilai23+ ", BIZZ, " +nilai25+ ", FIZZBIZZ, " +nilai27+ ", FIZZ, " +nilai29+ ", " +nilai30+ ", " +nilai31+ ", BIZZ, " +nilai33+ ", " +nilai34+ ", " +nilai35+ ", FIZZ, " +nilai37+ ", " +nilai38+ ", FIZZBIZZ, BIZZ, " +nilai41+ ", " +nilai42+ ", " +nilai43+ ", FIZZ, " +nilai45+ ", " +nilai46+ ", " +nilai47+ ", BIZZ, " +nilai49+ ", " +nilai50+ ", " +nilai51+ ", FIZZBIZZ, " +nilai53+ ", " +nilai54+ ", " +nilai55+ ", " +nilai56+ ", " +nilai57+ ", " +nilai58+ ", " +nilai59+ ", FIZZ, " + nilai61+ ", " +nilai62+ ", " +nilai63+ ", BIZZ, FIZZBIZZ, " +nilai66+ ", " +nilai67+ ", FIZZ, " +nilai69+ ", " +nilai70+ ", " +nilai71+ ", BIZZ, " +nilai73+ ", " +nilai74+ ", " +nilai75+ ", " +nilai76+ ", " +nilai77+ ", FIZZBIZZ, " +nilai79+ ", BIZZ, " +nilai81+ ", " +nilai82+ ", " +nilai83+ ", FIZZ, " +nilai85+ ", " +nilai86+ ", " +nilai87+ ", BIZZ, " +nilai89+ ", " +nilai90+ ", FIZZBIZZ, FIZZ, " +nilai93+ ", " +nilai94+ ", " +nilai95+ ", BIZZ, " +nilai97+ ", " +nilai98+ ", " +nilai99+ ", FIZZ");				
			}
		}
		
	}
}

/*
2. >> 
Nilai angka 1-100. Setiap inputan memiliki keistimewaan. 
Tampilkan fizz dari setiap urutan untuk nilai kelipatan 4. 
Tampilkan bizz dari setiap urutan untuk nilai kelipatan 8.
Tampilkan fizzbizz dari setiap urutan untuk nilai kelipatan 13.
Apabila ada nilai yang memiliki kelipatan yang sama (misal : 4 dan 8) 
prioritaskan untuk kelipatan yang lebih besar

Inputan : 20

Nilai yang akan muncul ==========
1, 2, 3, FIZZ, 5, 6, 7, BIZZ, 9, 10, 11, FIZZ, FIZZBIZZ, 14, 15, BIZZ, 17, 18, 19, FIZZ

32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100
32, 40, 48, 56, 64, 72, 80, 88, 96, 
39, 52, 65, 78, 91
*/
