/*
	 Program     : Soal 2 - Fizz Bizz 
     Creator     : Khairil
     Created At  : 14 Mei 2018 20:55 PM     
     Updated By  : 
     Update Date : 
*/
import java.util.Scanner;

public class FizzBizz {
	public static void main(String[] args) {
		Scanner keyboard = new Scanner(System.in);
		String fizz, bizz, fizzbizz;
		int nilai, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99, a100;

		fizz = "FIZZ";
		bizz = "BIZZ";
		fizzbizz = "FIZZ BIZZ";
		
		a1 = 1; a2 = 2; a3 = 3; a4 = 4; a5 = 5; a6 = 6; a7 = 7; a8 = 8; a9 = 9; a10 = 10;
		a11 = 11; a12 = 12; a13 = 13; a14 = 14; a15 = 15; a16 = 16; a17 = 17; a18 = 18; a19 = 19; a20 = 20;
		a21 = 21; a22 = 22; a23 = 23; a24 = 24; a25 = 25; a26 = 26; a27 = 27; a28 = 28; a29 = 29; a30 = 30;
		a31 = 31; a32 = 32; a33 = 33; a34 = 34; a35 = 35; a36 = 36; a37 = 37; a38 = 38; a39 = 39; a40 = 40;
		a41 = 41; a42 = 42; a43 = 43; a44 = 44; a45 = 45; a46 = 46; a47 = 47; a48 = 48; a49 = 49; a50 = 50;
		a51 = 51; a52 = 52; a53 = 53; a54 = 54; a55 = 55; a56 = 56; a57 = 57; a58 = 58; a59 = 59; a60 = 60;
		a61 = 61; a62 = 62; a63 = 63; a64 = 64; a65 = 65; a66 = 66; a67 = 67; a68 = 68; a69 = 69; a70 = 70;
		a71 = 71; a72 = 72; a73 = 73; a74 = 74; a75 = 75; a76 = 76; a77 = 77; a78 = 78; a79 = 79; a80 = 80;
		a81 = 81; a82 = 82; a83 = 83; a84 = 84; a85 = 85; a86 = 86; a87 = 87; a88 = 88; a89 = 89; a90 = 90;
		a91 = 91; a92 = 92; a93 = 93; a94 = 94; a95 = 95; a96 = 96; a97 = 97; a98 = 98; a99 = 99; a100 = 100;

		System.out.print("=============================");
		System.out.print("Tebak FizzBizz");
		System.out.println();
		System.out.print( "Masukkan Nilai  : (max 100)  " );
		nilai = keyboard.nextInt();
		System.out.println(" Nilai yang muncul :");		
		if(nilai == a1) {
			System.out.println(a1);
		}
		else if(nilai == a2) {
			System.out.println(a1 + ", " + a2);
		}
		else if(nilai == a3) {
			System.out.println(a1 + ", " + a2 + ", " + a3);
		}
		else if(nilai == a4) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz);
		}
		else if(nilai == a5) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5);
		}
		else if(nilai == a6) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6);
		}
		else if(nilai == a7) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7);
		}
		else if(nilai == a8) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz);
		}
		else if(nilai == a9) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9);
		}
		else if(nilai == a10) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10);
		}
		else if(nilai == a11) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11);
		}
		else if(nilai == a12) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz);
		}
		else if(nilai == a13) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz);
		}
		else if(nilai == a14) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14);
		}
		else if(nilai == a15) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15);
		}
		else if(nilai == a16) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz);
		}
		else if(nilai == a17) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17);
		}
		else if(nilai == a18) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18);
		}
		else if(nilai == a19) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19);
		}
		else if(nilai == a20) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz);
		}
		else if(nilai == a21) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21);
		}
		else if(nilai == a22) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22);
		}
		else if(nilai == a23) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23);
		}
		else if(nilai == a24) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz);
		}
		else if(nilai == a25) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25);
		}
		else if(nilai == a26) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz);
		}
		else if(nilai == a27) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27);
		}
		else if(nilai == a28) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz);
		}
		else if(nilai == a29) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29);
		}
		else if(nilai == a30) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30);
		}
		else if(nilai == a31) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31);
		}
		else if(nilai == a32) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz);
		}
		else if(nilai == a33) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33);
		}
		else if(nilai == a34) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34);
		}
		else if(nilai == a35) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35);
		}
		else if(nilai == a36) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz);
		}
		else if(nilai == a37) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37);
		}
		else if(nilai == a38) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38);
		}
		else if(nilai == a39) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz);
		}
		else if(nilai == a40) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz);
		}
		else if(nilai == a41) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41);
		}
		else if(nilai == a42) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42);
		}
		else if(nilai == a43) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43);
		}
		else if(nilai == a44) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz);
		}
		else if(nilai == a45) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45);
		}
		else if(nilai == a46) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46);
		}
		else if(nilai == a47) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47);
		}
		else if(nilai == a48) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz);
		}
		else if(nilai == a49) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49);
		}
		else if(nilai == a50) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50);
		}
		else if(nilai == a51) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51);
		}
		else if(nilai == a52) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz);
		}
		else if(nilai == a53) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53);
		}
		else if(nilai == a54) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54);
		}
		else if(nilai == a55) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55);
		}
		else if(nilai == a56) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz);
		}
		else if(nilai == a57) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57);
		}
		else if(nilai == a58) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58);
		}
		else if(nilai == a59) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59);
		}
		else if(nilai == a60) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz);
		}
		else if(nilai == a61) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61);
		}
		else if(nilai == a62) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62);
		}
		else if(nilai == a63) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63);
		}
		else if(nilai == a64) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz);
		}
		else if(nilai == a65) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz);
		}
		else if(nilai == a66) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66);
		}
		else if(nilai == a67) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67);
		}
		else if(nilai == a68) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz);
		}
		else if(nilai == a69) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69);
		}
		else if(nilai == a70) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70);
		}
		else if(nilai == a71) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71);
		}
		else if(nilai == a72) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz);
		}
		else if(nilai == a73) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73);
		}
		else if(nilai == a74) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74);
		}
		else if(nilai == a75) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75);
		}
		else if(nilai == a76) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz);
		}
		else if(nilai == a77) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77);
		}
		else if(nilai == a78) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz);
		}
		else if(nilai == a79) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79);
		}
		else if(nilai == a80) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz);
		}
		else if(nilai == a81) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81);
		}
		else if(nilai == a82) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82);
		}
		else if(nilai == a83) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83);
		}
		else if(nilai == a84) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz);
		}
		else if(nilai == a85) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85);
		}
		else if(nilai == a86) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86);
		}
		else if(nilai == a87) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87);
		}
		else if(nilai == a88) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz);
		}
		else if(nilai == a89) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89);
		}
		else if(nilai == a90) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90);
		}
		else if(nilai == a91) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz);
		}
		else if(nilai == a92) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz);
		}
		else if(nilai == a93) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz + ", " + a93);
		}
		else if(nilai == a94) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz + ", " + a93 + ", " + a94);
		}
		else if(nilai == a95) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz + ", " + a93 + ", " + a94 + ", " + a95);
		}
		else if(nilai == a96) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz + ", " + a93 + ", " + a94 + ", " + a95 + ", " + bizz);
		}
		else if(nilai == a97) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz + ", " + a93 + ", " + a94 + ", " + a95 + ", " + bizz + ", " + a97);
		}
		else if(nilai == a98) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz + ", " + a93 + ", " + a94 + ", " + a95 + ", " + bizz + ", " + a97 + ", " + a98);
		}
		else if(nilai == a99) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz + ", " + a93 + ", " + a94 + ", " + a95 + ", " + bizz + ", " + a97 + ", " + a98 + ", " + a99);
		}
		else if(nilai == a100) {
			System.out.println(a1 + ", " + a2 + ", " + a3 + ", " + fizz + ", " + a5 + ", " + a6 + ", " + a7 + ", " + bizz + ", " + a9 + ", " + a10 + ", " + a11 + ", " + fizz + ", " + fizzbizz + ", " + a14 + ", " + a15 + ", " + bizz + ", " + a17 + ", " + a18 + ", " + a19 + ", " + fizz + ", " + a21 + ", " + a22 + ", " + a23 + ", " + bizz + ", " + a25 + ", " + fizzbizz + ", " + a27 + ", " + fizz + ", " + a29 + ", " + a30 + ", " + a31 + ", " + bizz + ", " + a33 + ", " + a34 + ", " + a35 + ", " + fizz + ", " + a37 + ", " + a38 + ", " + fizzbizz + ", " + bizz + ", " + a41 + ", " + a42 + ", " + a43 + ", " + fizz + ", " + a45 + ", " + a46 + ", " + a47 + ", " + bizz + ", " + a49 + ", " + a50 + ", " + a51 + ", " + fizzbizz + ", " + a53 + ", " + a54 + ", " + a55 + ", " + bizz + ", " + a57 + ", " + a58 + ", " + a59 + ", " + fizz + ", " + a61 + ", " + a62 + ", " + a63 + ", " + fizz + ", " + fizzbizz + ", " + a66 + ", " + a67 + ", " + fizz + ", " + a69 + ", " + a70 + ", " + a71 + ", " + bizz + ", " + a73 + ", " + a74 + ", " + a75 + ", " + fizz + ", " + a77 + ", " + fizzbizz + ", " + a79 + ", " + bizz + ", " + a81+ ", " + a82 + ", " + a83 + ", " + fizz + ", " + a85 + ", " + a86 + ", " + a87 + ", " + bizz + ", " + a89 + ", " + a90 + ", " + fizzbizz + ", " + fizz + ", " + a93 + ", " + a94 + ", " + a95 + ", " + bizz + ", " + a97 + ", " + a98 + ", " + a99 + ", " + a100);
		}		
		else if(nilai < a1 || nilai > a100) {
			System.out.println("Inputan Max 100 tidak boleh kurang dari 0");
		}
	}
}